# anomaly_detection/config/config.yaml 
wandb_project_name: "VCAE"

# Data settings
data_path: 'data/BFO_a-0090_dark_ref_corrected.dm3'
energy_range: [420, 820] 
batch_size: 1
num_workers: 4

# Model settings
device: 'cuda'  # or 'cpu'
latent_dim: 48

# Training settings
learning_rate: 1e-4
lr_patience: 10
lr_factor: 0.5
kl_weight: 1
clip_value: 3.53
epochs: 300

# Preprocessing settings
image_size: 24
sigma: 0.5
xy_window: 3
anomaly_indices: [18] # if you want to exclude a certain shard index from the training set
sliding_window_stride: 24 
scaling_method: 'robust_minmax'